apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-workspace-quota
  namespace: devcontainers
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"
    count/pods: "3"
